project/src/cart/urls.py
from django.urls import path
from src.cart.views import *

app_name = 'cart'
urlpatterns = [
    path('add-to-cart/', view=add_to_cart,name='add-to-cart'),
]

project/src/product/urls.py
from django.urls import path
from src.product.views import ProductListView

app_name = 'product'
urlpatterns = [
    path('', view=ProductListView.as_view(), name='home'),
]

project/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from src.user.views import registration, login_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('src.product.urls')),
    path('cart/', include('src.cart.urls')),
    path('register/', registration, name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/src/cart/models.py
from django.db import models
from src.utility.models import BaseModel
from src.user.models import CustomUser
from src.cart.managers import CartManager
# Create your models here.


class Cart(BaseModel):

    objects = CartManager()

    owner = models.ForeignKey(CustomUser, related_name='user_cart', null=True, on_delete=models.CASCADE)
    

project/src/product/models.py
from django.db import models
from src.utility.models import BaseModel
from field_history.tracker import FieldHistoryTracker
import uuid
import pathlib
from django.conf.global_settings import MEDIA_ROOT

# Create your models here.
class Product(BaseModel):
    def path_to_image_product(self, filename):
        extension = pathlib.Path(filename).suffix
        new_filename = str(uuid.uuid4()) + extension
        return f'product/images/{new_filename}'

    name = models.CharField(max_length=300, default='')
    description = models.CharField(max_length=5000, default='')
    price = models.DecimalField(max_digits=8, decimal_places=2, default=999999.99)
    discount = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    image = models.ImageField('image', null=True, upload_to=path_to_image_product)

    field_history = FieldHistoryTracker(['price'])

    def __str__(self):
        return self.name

project/src/user/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from src.utility.models import BaseModel
import pathlib
import uuid

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin, BaseModel):

    def path_to_profile_image(self, filename):
        extension = pathlib.Path(filename).suffix
        new_filename = str(uuid.uuid4()) + extension
        return f'user/images/{new_filename}'

    email = models.EmailField(_('email address'), unique=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True, null=True)
    last_login = models.DateTimeField(auto_now=True, null=True)
    profile_image = models.ImageField(upload_to=path_to_profile_image, default='user/images/default-profile.jpg')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def delete(self):
        self.is_active = False
        super().delete()

    def has_perm(self, perm, obj=None):
        return self.is_admin or self.is_superuser

    def has_module_perms(self, app_label: str) -> bool:
        return True

    def __str__(self):
        return self.email

project/src/utility/models.py
from django.db import models

# Create your models here.
import uuid
from django.db import models
from safedelete.models import SafeDeleteModel
from safedelete import SOFT_DELETE_CASCADE


class BaseModel(SafeDeleteModel):
    _safedelete_policy = SOFT_DELETE_CASCADE

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Meta:
        abstract = True

project/src/user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = CustomUser
        fields = ('email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        if CustomUser.objects.filter(email=email).first():
            raise forms.ValidationError(f"Email {email} já está em uso")
        return email


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)


class CustomUserLoginForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'password')

project/src/cart/views.py
from django.http.response import JsonResponse
from src.product.models import Product
import json
# Create your views here.

def is_ajax(request):
    return request.headers.get('x-requested-with') == 'XMLHttpRequest'

def add_to_cart(request, *args, **kwargs):
    if is_ajax(request):
        body = json.loads(request.body)
        product_id = body.get('product')
        action = body.get('action')
        product = Product.objects.filter(id=product_id)
        if request.user.is_authenticated:
            cart = request.user.user_cart.last()
            cart.update_item(product, action)
            
    return JsonResponse({'status': 'ok'})

project/src/product/views.py
from django.shortcuts import render
from django.views.generic import ListView
from src.product.models import Product
from django.core.exceptions import ImproperlyConfigured
from django.db.models import Q
# Create your views here.

class ProductListView(ListView):
    model = Product
    context_object_name = 'products'
    paginate_by = 10

    def get_queryset(self):

        if self.request.GET.get('q'):
            q = self.request.GET['q']
            queryset = Product.objects.filter(Q(name__icontains=q) | Q(description__icontains=q))
        else:
            if self.queryset is not None:
                queryset = self.queryset
                if hasattr(queryset, '_clone'):
                    queryset = queryset._clone()
            elif self.model is not None:
                queryset = self.model._default_manager.all()
            else:
                raise ImproperlyConfigured(u"'%s' must define 'queryset' or 'model'"
                                        % self.__class__.__name__)
        return queryset

project/src/user/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, HttpResponse, redirect
from src.user.forms import CustomUserCreationForm, CustomUserLoginForm


def registration(request, *args, **kwargs):
    if request.user.is_authenticated:
        return HttpResponse(f"Você já está logado, mané")
    context = {}
    if request.POST:
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            authenticate(email=request.POST.get('email'), password=request.POST.get('password1'))
            login(request, user)
            return redirect("product:home")
        else:
            context['registration_form'] = form
    return render(request, 'user/registration.html', context=context)


def login_view(request, *args, **kwargs):
    if request.user.is_authenticated:
        return HttpResponse(f"Você já está logado, mané")
    context = {}
    if request.POST:
        form = CustomUserLoginForm(request.POST)
        user = authenticate(email=request.POST.get('email'),password=request.POST.get('password'))
        if user:
            login(request, user)
            return redirect("product:home")
        else:
            context['login_form'] = form
    return render(request, 'user/login.html', context=context)
    

project/src/utility/views.py
from django.shortcuts import render

# Create your views here.

project/src/product/templates/product/product_list.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<style>
    .product-card {
        min-width: 150px;
    }

    button,
    input[type="submit"],
    input[type="reset"],
    button:active,
    button:focus {
        background: none;
        color: inherit;
        border: none;
        padding: 0;
        font: inherit;
        cursor: pointer;
        outline: inherit;
    }
</style>
<div style="display: flex; justify-content: center;">
    <form method="GET">
        <label for="search">Search</label>
        <input type="text" id="search" name="q" value="{{ request.GET.q }}">
    </form>
</div>
<div style="display: flex; justify-content: center; align-items: center; gap: 2em; flex-wrap: wrap;">
    {% for product in products %}
    <div class="card">
        <div class="card-image waves-effect waves-block waves-light">
            {% if product.image %}
            <img class="activator" style="object-fit: contain; max-width: 200px;" src="{{ product.image.url }}"
                alt="teste">
            {% endif %}
        </div>
        <div class="card-content">
            <p class="card-title activator grey-text text-darken-4">{{ product.name }}</p>
            <p>R$ {{ product.price }}</p>
            <span><button class="add-to-cart-button " data-product="{{ product.id }}" data-action="add"
                    value="{{ product.id }}"><i class="material-icons">add_shopping_cart</i></button></span>
            <span><a href="#">View more</a></span>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">{{ product.name }}<i
                    class="material-icons right">close</i></span>
            <p>{{ product.description }}</p>
        </div>
    </div>
    {% endfor %}
</div>
<div style="display: flex; justify-content: center; align-items: bottom;">
    {% if request.GET.q and page_obj.has_previous %}
    <a href="?q={{ request.GET.q }}&page={{ page_obj.previous_page_number }}">
        &laquo;&nbsp;Previous
    </a>
    {% elif page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">&laquo;&nbsp;Previous</a>
    {% endif %}
    {% if request.GET.q and page_obj.has_next %}
    <a href="?q={{ request.GET.q }}&page={{ page_obj.next_page_number }}">
        Next&nbsp;&raquo;
    </a>
    {% elif page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Next&nbsp;&raquo;</a>
    {% endif %}
</div>
<script>
    
    const products = document.getElementsByClassName('add-to-cart-button')
    for (var i = 0; i < products.length; i++){
        products[i].addEventListener('click', makeRain)
    }

    function makeRain() {
        url = "{% url 'cart:add-to-cart' %}"
        console.log(this)
        productId = this.dataset.product
        action = this.dataset.action
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                "X-CSRFToken": getCookie("csrftoken"),
                "X-Requested-With": "XMLHttpRequest",             
            },
            body: JSON.stringify({ 'productId': productId, 'action': action})
        })
            .then((response) => {
                return response.json()
            })
            .then((data) => {
                console.log('Data:', data)
            });
    }
</script>
{% endblock %}

project/src/user/templates/user/login.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div style="display: flex; justify-content: center; align-items: bottom;">
    <center>
      <img class="responsive-img" style="width: 250px;" src="https://i.imgur.com/ax0NCsK.gif" />
      <div class="section"></div>

      <h5 class="indigo-text">Please, login into your account</h5>
      <div class="section"></div>

      <div class="container">
        <div class="z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

          <form class="col s12" method="post">
              {% csrf_token %}
            <div class='row'>
              <div class='col s12'>
              </div>
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                <input class='validate' type='email' name='email' id='email' />
                <label for='email'>Enter your email</label>
              </div>
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                <input class='validate' type='password' name='password' id='password' />
                <label for='password'>Enter your password</label>
              </div>
              <label style='float: right;'>
								<a class='pink-text' href='#!'><b>Forgot Password?</b></a>
							</label>
            </div>

            <br />
            <center>
              <div class='row'>
                <button type='submit' name='btn_login' class='col s12 btn btn-large waves-effect indigo'>Login</button>
              </div>
            </center>
          </form>
        </div>
      </div>
      <a href="{% url 'registration' %}">Create account</a>
</center>
</div>
{% endblock %}

project/src/user/templates/user/registration.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

    <div style="display: flex; justify-content: center; align-items: bottom;">
        <center>
            <img class="responsive-img" style="width: 250px;" src="https://i.imgur.com/ax0NCsK.gif"/>
            <div class="section"></div>

            <h5 class="indigo-text">Please, login into your account</h5>
            <div class="section"></div>

            <div class="container">
                <div class="z-depth-1 grey lighten-4 row"
                     style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

                    <form class="col s12" method="post">
                        {% csrf_token %}
                        <div class='row'>
                            <div class='col s12'>
                            </div>
                        </div>

                        <div class='row'>
                            <div class='input-field col s12'>
                                <input class='validate' type='email' name='email' id='email'/>
                                <label for='email'>Enter your email</label>
                            </div>
                        </div>

                        <div class='row'>
                            <div class='input-field col s12'>
                                <input class='validate' type='password' name='password1' id='password1'/>
                                <label for='password'>Enter your password</label>
                            </div>
                            <div class='input-field col s12'>
                                <input class='validate' type='password' name='password2' id='password2'/>
                                <label for='password'>Match your password</label>
                            </div>
                            <label style='float: right;'>
                                <a class='pink-text' href='#!'><b>Forgot Password?</b></a>
                            </label>
                        </div>

                        <br/>
                        <center>
                            <div class='row'>
                                <button type='submit' name='btn_login'
                                        class='col s12 btn btn-large waves-effect indigo'>Register
                                </button>
                            </div>
                        </center>
                    </form>
                </div>
            </div>
            <a href="#!">Already have an account? Login </a>
        </center>
    </div>
{% endblock %}

project/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- Materialize Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="{% static 'base/js/cookies.js' %}"></script>

    <title>E-commerce boladão</title>
</head>
<body>
   <nav>
    <div class="nav-wrapper red">
      <a href="#!" class="brand-logo">Logo</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="sass.html">Cart</a></li>
        {% if not request.user.is_authenticated %}
        <li><a href="{% url 'login' %}">Login</a></li>
        <li><a href="{% url 'registration' %}">Register</a></li>
        {% else %}
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">Sass</a></li>
    <li><a href="badges.html">Components</a></li>
    <li><a href="collapsible.html">Javascript</a></li>
    <li><a href="mobile.html">Mobile</a></li>
  </ul>
{% block content %}
{% endblock %}
</body>
</html>